### ISSUE TITLE
Add s3 support

### ISSUE THREAD

**Issue by epsniff** [lytics/cloudstorage#5]
Ref:
https://github.com/aws/aws-sdk-go/blob/fd136b7571693211815b5c780eebcb52c37a1b46/service/s3/s3iface/interface.go#L12

https://github.com/aws/aws-sdk-go/blob/cb8f6e2243db557350e4ff8f786590881e4149b6/service/s3/api.go#L3407

**Comment by peczenyj** [comment]
Hello

Why the Copy and Move functions are not available on s3? any special reason?

**Comment by araddon** [comment]
No special reason,  just hadn't gotten to it yet created ticket for it https://github.com/lytics/cloudstorage/blob/27319609bc1c8b4108e8cbc652c5dcbcf6747145/google/store.go#L174

Will see if i can find time to get it in soon.
