### ISSUE TITLE
localfs NewWriter, should use O_TRUNC ?

### ISSUE THREAD

**Issue by mh-cbon** [lytics/cloudstorage#52]
hi,

when i read the doc about NewWriter it says,

```go
		// NewWriter returns a io.Writer that writes to a Cloud object
		// associated with this backing Store object.
		//
		// A new object will be created if an object with this name already exists.
		// Otherwise any previous object with the same name will be replaced.
		// The object will not be available (and any previous object will remain)
		// until Close has been called
		NewWriter(o string, metadata map[string]string) (io.WriteCloser, error)
```

however when using the localfs type, it appears the file is not truncated

- https://github.com/lytics/cloudstorage/blob/a14e59c8bb0724b36e7c465b73a87988012de18f/localfs/store.go#L247
- https://github.com/lytics/cloudstorage/blob/b738f5f5a70a634b2525f12c6abdbd4ad7f0f3cc/csbufio/writer.go#L16

What do you think ?

**Comment by araddon** [comment]
thanks for the report, and great write-up, will try to get some unit tests etc and address this soon.

**Comment by epsniff** [comment]
@araddon Ill take this one, I should have a PR up tomorrow.
