### ISSUE TITLE
awss3 List does not call query ApplyFilters

### ISSUE THREAD

**Issue by peczenyj** [lytics/cloudstorage#68]
the documentation of Query ApplyFilters says

```
// ApplyFilters is called as the last step in store.List() to filter out the
// results before they are returned.
```

but it is not true for awss3 ( and maybe for google )

**Comment by araddon** [comment]
We are thinking of deprecating this, making it responsibility of caller.   Will update tests, see if we can still support sorting, but remove this as a public feature.

**Comment by peczenyj** [comment]
oh nice. this works for me
