### ISSUE TITLE
localfs does not remove the cachefile on object.Close()

### ISSUE THREAD

**Issue by peczenyj** [lytics/cloudstorage#69]
on awss3 object.Close() remove the cachepath

https://github.com/lytics/cloudstorage/blob/master/awss3/store.go#L677

But localfs only remove on Release
https://github.com/lytics/cloudstorage/blob/master/localfs/store.go#L463

Not sure if it happens in other backends

**Comment by peczenyj** [comment]
Hi

Using `awss3` as backend, on create a new file and submit to s3 bucket, when we finish the sync/close the cachefile is removed with success, but the directory still exists ( with no files ).

It is not a big problem for me, but is there a way to remove the cachefile + path

For me, the workaround is: once I finish to process my files, I will remove all content of `/tmp` ( or what I define on the configuration ).

My project is a daemon, I will process files from one s3 bucket to another in my main loop, I don't want to create hundreds of empty directories so I will force delete.

**Comment by araddon** [comment]
Thanks for the report, will try to upgrade the tests to detect this and get patch in as soon as I can.

**Comment by epsniff** [comment]
Actually it looks localfs is the only remaining store that does't cleanup in Close().  I'd say, lets fix it and drop the Release func from the interface.

**Comment by epsniff** [comment]
Going to fix this in a small PR and then open up a new Issue to cleanup the release interface.

**Comment by epsniff** [comment]
@peczenyj - That second problem you mentioned seems worthy of it's own issue.   Could you create a new issue for cleaning up cachedirs when they become empty?   I also have comments about that, but I'll wait until you create a new issue.

**Comment by peczenyj** [comment]
> @peczenyj - That second problem you mentioned seems worthy of it's own issue. Could you create a new issue for cleaning up cachedirs when they become empty? I also have comments about that, but I'll wait until you create a new issue.

I rethink and seems the temporary directory is my responsibility. so i will be Explicit in create and clean it, and it will be fine.

of course will be great delete the files, and the empty dirs can be removed from time to time since it take less space.

thanks for your time!
